services:
  db:
    image: postgres:16-alpine
    container_name: postgres-reading-app
    restart: always
    environment:
      # .env から値を読み込みます
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      # PostgreSQLのデータ永続化パスはここです
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
    #volumes: これが重要です！これがないと、Dockerを止めるたびにDBに保存したデータ（本やメモ）が消えてしまいます。
    #         sql-data という領域を確保して、データを永続化しています。
    #container_name: 自由に変えられますが、プロジェクト名を入れると分かりやすくなります。

    # 起動
    # docker-compose up -d
    # 停止
    # docker-compose stop
    # 完全に削除
    # docker-compose down
